### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by JerryWho** [Fosome/garb#17]
I tried to run the tests via 'rake test' but it fails with the error

```
/usr/local/bin/ruby -I"lib:test" "/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/unit/garb/account_test.rb"   "test/unit/garb/authentication_request_test.rb" "test/unit/garb/data_request_test.rb" "test/unit/garb/filter_parameters_test.rb" "test/unit/garb/oauth_session_test.rb"     "test/unit/garb/operator_test.rb" "test/unit/garb/profile_test.rb" "test/unit/garb/report_parameter_test.rb" "test/unit/garb/report_response_test.rb"   "test/unit/garb/report_test.rb" "test/unit/garb/resource_test.rb" "test/unit/garb/session_test.rb" "test/unit/garb_test.rb" 
./test/unit/garb/account_test.rb:5: undefined method `context' for Garb::AccountTest:Class (NoMethodError)
from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `load'
from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5
from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `each'
from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5
rake aborted!
Command failed with status (1): [/usr/local/bin/ruby -I"lib:test" "/usr/loc...]
```

I installed the gem minitest but without any success. What's my fault?

Thanks,
Martin

**Comment by tpitale** [comment]
You're missing thoughtbot-shoulda

**Comment by scudco** [comment]
I had similar trouble getting the tests to run so I added explicit activates into the test_helper as well as merging in Jeremy Kemper's (working) changes in my fork. http://github.com/scudco/garb/commit/0a21cee0160a94878cec744ed8e6a5058cf214f5

Also I'm not sure why I needed to require activesupport explicitly, but demodulize wasn't available unless I did.

**Comment by tpitale** [comment]
Sorry, it isn't thoughtbot-shoulda, try using tpitale-shoulda. They have yet to accept my patch to add minitest support to shoulda.
